POST http://localhost:5000/api/admin/signup
Content-Type: application/json

{
  "name": "System Admin",
  "email": "admin@example.com",
  "password": "Admin@123",
  "bootstrapKey": "iamtheadmin"
}

### Admin Login ###
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@123"
}

###
GET http://localhost:5000/api/ngos/approved

###
GET http://localhost:5000/api/ngos/all

### Verify NGO (Admin Only)
PATCH http://localhost:5000/api/ngos/verify/69bbd50099a8229d7dce9208
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmMwNWU2MGRlNjUzZWRkNjAzM2EyZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MzkyOTk2MCwiZXhwIjoxNzc0MDE2MzYwfQ.oWjLBs1ZIAomegFFx72Uw4bDeXZfzFaP8mz0eYBIQZQ
Content-Type: application/json

###
GET http://localhost:5000/api/ngos/pending



